/*
 * Полная колода Таро (78 карт) с трактовками на русском и английском.
 * Full Tarot deck (78 cards) with Russian & English meanings.
 *
 * Структура карты / card shape:
 *   { id, suit, emoji,
 *     name: {ru, en},
 *     up:   {ru, en},   // в прямом положении / upright
 *     rev:  {ru, en} }  // в перевёрнутом положении / reversed
 */

const TAROT_DECK = [
  /* ============ СТАРШИЕ АРКАНЫ / MAJOR ARCANA ============ */
  { id: 0, suit: 'major', emoji: '🤡',
    name: { ru: '0 — Шут', en: '0 — The Fool' },
    up:  { ru: 'Новое начало, спонтанность, вера в путь и свобода духа.', en: 'New beginnings, spontaneity, a leap of faith and free spirit.' },
    rev: { ru: 'Безрассудство, наивность, страх перемен и упущенный шанс.', en: 'Recklessness, naivety, fear of change and missed opportunity.' } },
  { id: 1, suit: 'major', emoji: '🪄',
    name: { ru: 'I — Маг', en: 'I — The Magician' },
    up:  { ru: 'Сила воли, мастерство, проявление желаний и действие.', en: 'Willpower, skill, manifestation and decisive action.' },
    rev: { ru: 'Манипуляция, неиспользованный талант, обман и сомнения.', en: 'Manipulation, untapped talent, deceit and self-doubt.' } },
  { id: 2, suit: 'major', emoji: '🌙',
    name: { ru: 'II — Верховная Жрица', en: 'II — The High Priestess' },
    up:  { ru: 'Интуиция, тайна, внутренний голос и скрытое знание.', en: 'Intuition, mystery, the inner voice and hidden knowledge.' },
    rev: { ru: 'Игнорирование интуиции, секреты, поверхностность.', en: 'Ignored intuition, secrets and surface-level thinking.' } },
  { id: 3, suit: 'major', emoji: '👑',
    name: { ru: 'III — Императрица', en: 'III — The Empress' },
    up:  { ru: 'Изобилие, забота, плодородие и творческий расцвет.', en: 'Abundance, nurturing, fertility and creative flourishing.' },
    rev: { ru: 'Зависимость, творческий блок, пренебрежение собой.', en: 'Dependence, creative block and self-neglect.' } },
  { id: 4, suit: 'major', emoji: '🏛️',
    name: { ru: 'IV — Император', en: 'IV — The Emperor' },
    up:  { ru: 'Структура, власть, стабильность и здоровый контроль.', en: 'Structure, authority, stability and healthy control.' },
    rev: { ru: 'Тирания, упрямство, потеря контроля или жёсткость.', en: 'Tyranny, rigidity and loss of control.' } },
  { id: 5, suit: 'major', emoji: '⛪',
    name: { ru: 'V — Иерофант', en: 'V — The Hierophant' },
    up:  { ru: 'Традиция, наставничество, вера и общие ценности.', en: 'Tradition, mentorship, belief and shared values.' },
    rev: { ru: 'Бунт против норм, догматизм, поиск своего пути.', en: 'Rebellion against norms, dogma and finding your own path.' } },
  { id: 6, suit: 'major', emoji: '💞',
    name: { ru: 'VI — Влюблённые', en: 'VI — The Lovers' },
    up:  { ru: 'Любовь, гармония, важный выбор и союз ценностей.', en: 'Love, harmony, a meaningful choice and union of values.' },
    rev: { ru: 'Разлад, неверный выбор, дисбаланс в отношениях.', en: 'Disharmony, poor choices and imbalance in relationships.' } },
  { id: 7, suit: 'major', emoji: '🏇',
    name: { ru: 'VII — Колесница', en: 'VII — The Chariot' },
    up:  { ru: 'Победа, целеустремлённость, контроль и движение вперёд.', en: 'Victory, determination, control and forward momentum.' },
    rev: { ru: 'Потеря направления, противоречия, отсутствие воли.', en: 'Lack of direction, opposition and weak willpower.' } },
  { id: 8, suit: 'major', emoji: '🦁',
    name: { ru: 'VIII — Сила', en: 'VIII — Strength' },
    up:  { ru: 'Внутренняя сила, мужество, терпение и самообладание.', en: 'Inner strength, courage, patience and composure.' },
    rev: { ru: 'Неуверенность, слабость, подавленные эмоции.', en: 'Self-doubt, weakness and suppressed emotions.' } },
  { id: 9, suit: 'major', emoji: '🏮',
    name: { ru: 'IX — Отшельник', en: 'IX — The Hermit' },
    up:  { ru: 'Самопознание, уединение, поиск истины и мудрость.', en: 'Soul-searching, solitude, seeking truth and wisdom.' },
    rev: { ru: 'Изоляция, одиночество, отказ от помощи.', en: 'Isolation, loneliness and withdrawal from others.' } },
  { id: 10, suit: 'major', emoji: '🎡',
    name: { ru: 'X — Колесо Фортуны', en: 'X — Wheel of Fortune' },
    up:  { ru: 'Удача, поворот судьбы, циклы и благоприятные перемены.', en: 'Luck, a turning point, cycles and favourable change.' },
    rev: { ru: 'Невезение, застой, сопротивление неизбежному.', en: 'Bad luck, stagnation and resisting the inevitable.' } },
  { id: 11, suit: 'major', emoji: '⚖️',
    name: { ru: 'XI — Справедливость', en: 'XI — Justice' },
    up:  { ru: 'Честность, ответственность, причина и следствие, баланс.', en: 'Fairness, accountability, cause and effect, balance.' },
    rev: { ru: 'Несправедливость, нечестность, уход от ответственности.', en: 'Injustice, dishonesty and avoiding accountability.' } },
  { id: 12, suit: 'major', emoji: '🙃',
    name: { ru: 'XII — Повешенный', en: 'XII — The Hanged Man' },
    up:  { ru: 'Пауза, новый взгляд, отпускание и осознанная жертва.', en: 'Pause, new perspective, surrender and meaningful sacrifice.' },
    rev: { ru: 'Застревание, сопротивление, бессмысленные жертвы.', en: 'Stalling, resistance and pointless sacrifice.' } },
  { id: 13, suit: 'major', emoji: '💀',
    name: { ru: 'XIII — Смерть', en: 'XIII — Death' },
    up:  { ru: 'Завершение, трансформация, обновление и новый этап.', en: 'Endings, transformation, renewal and a new chapter.' },
    rev: { ru: 'Страх перемен, застой, удержание прошлого.', en: 'Fear of change, stagnation and clinging to the past.' } },
  { id: 14, suit: 'major', emoji: '🕊️',
    name: { ru: 'XIV — Умеренность', en: 'XIV — Temperance' },
    up:  { ru: 'Баланс, терпение, гармония и золотая середина.', en: 'Balance, patience, harmony and moderation.' },
    rev: { ru: 'Крайности, дисбаланс, нетерпение и излишества.', en: 'Extremes, imbalance, impatience and excess.' } },
  { id: 15, suit: 'major', emoji: '😈',
    name: { ru: 'XV — Дьявол', en: 'XV — The Devil' },
    up:  { ru: 'Зависимости, привязанности, соблазны и иллюзия плена.', en: 'Addiction, attachment, temptation and illusory bondage.' },
    rev: { ru: 'Освобождение, разрыв оков, возврат контроля.', en: 'Release, breaking free and reclaiming control.' } },
  { id: 16, suit: 'major', emoji: '🗼',
    name: { ru: 'XVI — Башня', en: 'XVI — The Tower' },
    up:  { ru: 'Внезапные перемены, крах иллюзий, очищающее потрясение.', en: 'Sudden upheaval, collapse of illusions and cleansing shock.' },
    rev: { ru: 'Оттягивание неизбежного, страх краха, медленный распад.', en: 'Delaying the inevitable, fear of disaster and slow decline.' } },
  { id: 17, suit: 'major', emoji: '⭐',
    name: { ru: 'XVII — Звезда', en: 'XVII — The Star' },
    up:  { ru: 'Надежда, вдохновение, исцеление и вера в будущее.', en: 'Hope, inspiration, healing and faith in the future.' },
    rev: { ru: 'Уныние, потеря веры, разочарование.', en: 'Despair, loss of faith and disappointment.' } },
  { id: 18, suit: 'major', emoji: '🌕',
    name: { ru: 'XVIII — Луна', en: 'XVIII — The Moon' },
    up:  { ru: 'Иллюзии, тревога, подсознание и неясность.', en: 'Illusion, anxiety, the subconscious and uncertainty.' },
    rev: { ru: 'Прояснение, освобождение от страхов, правда выходит наружу.', en: 'Clarity, releasing fear and truth coming to light.' } },
  { id: 19, suit: 'major', emoji: '☀️',
    name: { ru: 'XIX — Солнце', en: 'XIX — The Sun' },
    up:  { ru: 'Радость, успех, жизненная сила и ясность.', en: 'Joy, success, vitality and clarity.' },
    rev: { ru: 'Временные тучи, пессимизм, отложенный успех.', en: 'Temporary clouds, pessimism and delayed success.' } },
  { id: 20, suit: 'major', emoji: '📯',
    name: { ru: 'XX — Суд', en: 'XX — Judgement' },
    up:  { ru: 'Пробуждение, переоценка, прощение и зов судьбы.', en: 'Awakening, reckoning, forgiveness and a calling.' },
    rev: { ru: 'Самокритика, сомнения, игнорирование зова.', en: 'Self-doubt, harsh judgement and ignoring the call.' } },
  { id: 21, suit: 'major', emoji: '🌍',
    name: { ru: 'XXI — Мир', en: 'XXI — The World' },
    up:  { ru: 'Завершение, целостность, достижение и гармония.', en: 'Completion, wholeness, accomplishment and harmony.' },
    rev: { ru: 'Незавершённость, задержки, недостигнутая цель.', en: 'Incompletion, delays and unfinished goals.' } },

  /* ============ ЖЕЗЛЫ / WANDS (огонь, действие) ============ */
  { id: 22, suit: 'wands', emoji: '🔥',
    name: { ru: 'Туз Жезлов', en: 'Ace of Wands' },
    up:  { ru: 'Искра вдохновения, новый импульс и творческая энергия.', en: 'A spark of inspiration, new drive and creative energy.' },
    rev: { ru: 'Задержка, нехватка мотивации, угасший энтузиазм.', en: 'Delays, lack of motivation and faded enthusiasm.' } },
  { id: 23, suit: 'wands', emoji: '🔥',
    name: { ru: 'Двойка Жезлов', en: 'Two of Wands' },
    up:  { ru: 'Планирование, выбор пути и взгляд в будущее.', en: 'Planning, choosing a path and looking ahead.' },
    rev: { ru: 'Страх неизвестности, нерешительность, плохое планирование.', en: 'Fear of the unknown, indecision and poor planning.' } },
  { id: 24, suit: 'wands', emoji: '🔥',
    name: { ru: 'Тройка Жезлов', en: 'Three of Wands' },
    up:  { ru: 'Расширение, прогресс и предвидение результатов.', en: 'Expansion, progress and foresight of results.' },
    rev: { ru: 'Задержки, препятствия, узкий взгляд.', en: 'Delays, obstacles and a narrow outlook.' } },
  { id: 25, suit: 'wands', emoji: '🔥',
    name: { ru: 'Четвёрка Жезлов', en: 'Four of Wands' },
    up:  { ru: 'Праздник, гармония дома, стабильность и радость.', en: 'Celebration, harmony at home, stability and joy.' },
    rev: { ru: 'Напряжение в семье, отложенный праздник, неустроенность.', en: 'Tension at home, postponed celebration and instability.' } },
  { id: 26, suit: 'wands', emoji: '🔥',
    name: { ru: 'Пятёрка Жезлов', en: 'Five of Wands' },
    up:  { ru: 'Конкуренция, споры, борьба и столкновение мнений.', en: 'Competition, conflict, struggle and clashing views.' },
    rev: { ru: 'Избегание конфликта, внутренняя борьба, перемирие.', en: 'Avoiding conflict, inner tension and a truce.' } },
  { id: 27, suit: 'wands', emoji: '🔥',
    name: { ru: 'Шестёрка Жезлов', en: 'Six of Wands' },
    up:  { ru: 'Победа, признание, успех и заслуженная похвала.', en: 'Victory, recognition, success and well-earned praise.' },
    rev: { ru: 'Отсутствие признания, сомнения, падение с пьедестала.', en: 'Lack of recognition, self-doubt and a fall from grace.' } },
  { id: 28, suit: 'wands', emoji: '🔥',
    name: { ru: 'Семёрка Жезлов', en: 'Seven of Wands' },
    up:  { ru: 'Отстаивание позиции, защита и стойкость.', en: 'Standing your ground, defence and perseverance.' },
    rev: { ru: 'Уступки, перегрузка, потеря позиций.', en: 'Giving up, overwhelm and losing ground.' } },
  { id: 29, suit: 'wands', emoji: '🔥',
    name: { ru: 'Восьмёрка Жезлов', en: 'Eight of Wands' },
    up:  { ru: 'Быстрые события, движение, новости и скорость.', en: 'Swift events, movement, news and momentum.' },
    rev: { ru: 'Задержки, суета, разрозненность усилий.', en: 'Delays, frustration and scattered energy.' } },
  { id: 30, suit: 'wands', emoji: '🔥',
    name: { ru: 'Девятка Жезлов', en: 'Nine of Wands' },
    up:  { ru: 'Стойкость, последний рубеж, упорство несмотря на усталость.', en: 'Resilience, last stand and persistence despite fatigue.' },
    rev: { ru: 'Истощение, паранойя, нежелание сдаваться во вред себе.', en: 'Exhaustion, paranoia and stubbornness to your own harm.' } },
  { id: 31, suit: 'wands', emoji: '🔥',
    name: { ru: 'Десятка Жезлов', en: 'Ten of Wands' },
    up:  { ru: 'Бремя, перегрузка, ответственность и тяжёлая ноша.', en: 'Burden, overload, responsibility and a heavy load.' },
    rev: { ru: 'Освобождение от груза, делегирование, отказ от лишнего.', en: 'Releasing the burden, delegating and letting go.' } },
  { id: 32, suit: 'wands', emoji: '🔥',
    name: { ru: 'Паж Жезлов', en: 'Page of Wands' },
    up:  { ru: 'Любопытство, энтузиазм, новые идеи и жажда приключений.', en: 'Curiosity, enthusiasm, fresh ideas and a thirst for adventure.' },
    rev: { ru: 'Неуверенность, разбросанность, незрелые планы.', en: 'Insecurity, scattered focus and immature plans.' } },
  { id: 33, suit: 'wands', emoji: '🔥',
    name: { ru: 'Рыцарь Жезлов', en: 'Knight of Wands' },
    up:  { ru: 'Энергия, страсть, смелые действия и приключения.', en: 'Energy, passion, bold action and adventure.' },
    rev: { ru: 'Импульсивность, спешка, незавершённые дела.', en: 'Impulsiveness, haste and unfinished projects.' } },
  { id: 34, suit: 'wands', emoji: '🔥',
    name: { ru: 'Королева Жезлов', en: 'Queen of Wands' },
    up:  { ru: 'Уверенность, харизма, тепло и независимость.', en: 'Confidence, charisma, warmth and independence.' },
    rev: { ru: 'Ревность, неуверенность, требовательность.', en: 'Jealousy, insecurity and being demanding.' } },
  { id: 35, suit: 'wands', emoji: '🔥',
    name: { ru: 'Король Жезлов', en: 'King of Wands' },
    up:  { ru: 'Лидерство, видение, харизма и предприимчивость.', en: 'Leadership, vision, charisma and enterprise.' },
    rev: { ru: 'Деспотизм, импульсивность, завышенные ожидания.', en: 'Tyranny, impulsiveness and unrealistic expectations.' } },

  /* ============ КУБКИ / CUPS (вода, чувства) ============ */
  { id: 36, suit: 'cups', emoji: '💧',
    name: { ru: 'Туз Кубков', en: 'Ace of Cups' },
    up:  { ru: 'Новые чувства, любовь, открытое сердце и вдохновение.', en: 'New feelings, love, an open heart and inspiration.' },
    rev: { ru: 'Подавленные эмоции, пустота, закрытость.', en: 'Blocked emotions, emptiness and emotional withdrawal.' } },
  { id: 37, suit: 'cups', emoji: '💧',
    name: { ru: 'Двойка Кубков', en: 'Two of Cups' },
    up:  { ru: 'Союз, взаимность, гармония и партнёрство.', en: 'Union, mutuality, harmony and partnership.' },
    rev: { ru: 'Разлад, дисбаланс, разрыв связи.', en: 'Disharmony, imbalance and a broken bond.' } },
  { id: 38, suit: 'cups', emoji: '💧',
    name: { ru: 'Тройка Кубков', en: 'Three of Cups' },
    up:  { ru: 'Дружба, праздник, поддержка и совместная радость.', en: 'Friendship, celebration, support and shared joy.' },
    rev: { ru: 'Излишества, сплетни, изоляция от круга.', en: 'Overindulgence, gossip and isolation from your circle.' } },
  { id: 39, suit: 'cups', emoji: '💧',
    name: { ru: 'Четвёрка Кубков', en: 'Four of Cups' },
    up:  { ru: 'Апатия, переоценка, упущенные возможности.', en: 'Apathy, reevaluation and missed opportunities.' },
    rev: { ru: 'Новый интерес, принятие предложения, выход из хандры.', en: 'New interest, accepting an offer and emerging from gloom.' } },
  { id: 40, suit: 'cups', emoji: '💧',
    name: { ru: 'Пятёрка Кубков', en: 'Five of Cups' },
    up:  { ru: 'Сожаление, утрата, печаль и фокус на потерянном.', en: 'Regret, loss, sorrow and dwelling on what is gone.' },
    rev: { ru: 'Принятие, прощение, движение дальше.', en: 'Acceptance, forgiveness and moving on.' } },
  { id: 41, suit: 'cups', emoji: '💧',
    name: { ru: 'Шестёрка Кубков', en: 'Six of Cups' },
    up:  { ru: 'Ностальгия, тёплые воспоминания, невинность и доброта.', en: 'Nostalgia, fond memories, innocence and kindness.' },
    rev: { ru: 'Застревание в прошлом, идеализация, нежелание взрослеть.', en: 'Stuck in the past, idealising and refusing to grow up.' } },
  { id: 42, suit: 'cups', emoji: '💧',
    name: { ru: 'Семёрка Кубков', en: 'Seven of Cups' },
    up:  { ru: 'Выбор, иллюзии, мечты и фантазии.', en: 'Choices, illusions, dreams and fantasies.' },
    rev: { ru: 'Ясность, реалистичный выбор, отрезвление.', en: 'Clarity, a realistic choice and a reality check.' } },
  { id: 43, suit: 'cups', emoji: '💧',
    name: { ru: 'Восьмёрка Кубков', en: 'Eight of Cups' },
    up:  { ru: 'Уход, поиск смысла, оставление неудовлетворяющего.', en: 'Walking away, seeking meaning and leaving what no longer fulfils.' },
    rev: { ru: 'Страх перемен, метания, удержание изжившего.', en: 'Fear of change, drifting and clinging to the worn-out.' } },
  { id: 44, suit: 'cups', emoji: '💧',
    name: { ru: 'Девятка Кубков', en: 'Nine of Cups' },
    up:  { ru: 'Исполнение желаний, удовлетворение и благополучие.', en: 'Wishes fulfilled, contentment and well-being.' },
    rev: { ru: 'Неудовлетворённость, пустое довольство, жадность.', en: 'Dissatisfaction, hollow contentment and greed.' } },
  { id: 45, suit: 'cups', emoji: '💧',
    name: { ru: 'Десятка Кубков', en: 'Ten of Cups' },
    up:  { ru: 'Гармония, счастливая семья, эмоциональное изобилие.', en: 'Harmony, a happy family and emotional fulfilment.' },
    rev: { ru: 'Разлад в семье, разбитые идеалы, напряжение.', en: 'Family discord, broken ideals and tension.' } },
  { id: 46, suit: 'cups', emoji: '💧',
    name: { ru: 'Паж Кубков', en: 'Page of Cups' },
    up:  { ru: 'Чувствительность, творческая идея, приятная новость.', en: 'Sensitivity, a creative idea and pleasant news.' },
    rev: { ru: 'Эмоциональная незрелость, обидчивость, блок чувств.', en: 'Emotional immaturity, touchiness and blocked feelings.' } },
  { id: 47, suit: 'cups', emoji: '💧',
    name: { ru: 'Рыцарь Кубков', en: 'Knight of Cups' },
    up:  { ru: 'Романтика, идеализм, предложение из сердца.', en: 'Romance, idealism and an offer from the heart.' },
    rev: { ru: 'Капризность, нереалистичность, разочарование.', en: 'Moodiness, unrealistic ideals and disappointment.' } },
  { id: 48, suit: 'cups', emoji: '💧',
    name: { ru: 'Королева Кубков', en: 'Queen of Cups' },
    up:  { ru: 'Сострадание, забота, эмпатия и интуиция.', en: 'Compassion, care, empathy and intuition.' },
    rev: { ru: 'Эмоциональная нестабильность, созависимость, обида.', en: 'Emotional instability, codependency and resentment.' } },
  { id: 49, suit: 'cups', emoji: '💧',
    name: { ru: 'Король Кубков', en: 'King of Cups' },
    up:  { ru: 'Эмоциональная зрелость, баланс чувств и мудрый совет.', en: 'Emotional maturity, balanced feelings and wise counsel.' },
    rev: { ru: 'Подавленные эмоции, манипуляции, нестабильность.', en: 'Suppressed emotions, manipulation and volatility.' } },

  /* ============ МЕЧИ / SWORDS (воздух, разум) ============ */
  { id: 50, suit: 'swords', emoji: '⚔️',
    name: { ru: 'Туз Мечей', en: 'Ace of Swords' },
    up:  { ru: 'Ясность, прорыв, истина и новая идея.', en: 'Clarity, breakthrough, truth and a new idea.' },
    rev: { ru: 'Спутанность, недопонимание, отсутствие ясности.', en: 'Confusion, miscommunication and lack of clarity.' } },
  { id: 51, suit: 'swords', emoji: '⚔️',
    name: { ru: 'Двойка Мечей', en: 'Two of Swords' },
    up:  { ru: 'Трудный выбор, тупик, баланс и нерешительность.', en: 'A hard choice, stalemate, balance and indecision.' },
    rev: { ru: 'Выход из тупика, принятое решение, перегрузка информацией.', en: 'Breaking the deadlock, a decision made and information overload.' } },
  { id: 52, suit: 'swords', emoji: '⚔️',
    name: { ru: 'Тройка Мечей', en: 'Three of Swords' },
    up:  { ru: 'Боль, разочарование, разбитое сердце и горькая правда.', en: 'Pain, heartbreak, sorrow and a hard truth.' },
    rev: { ru: 'Исцеление, прощение, выход из боли.', en: 'Healing, forgiveness and recovery from pain.' } },
  { id: 53, suit: 'swords', emoji: '⚔️',
    name: { ru: 'Четвёрка Мечей', en: 'Four of Swords' },
    up:  { ru: 'Отдых, восстановление, пауза и тишина.', en: 'Rest, recovery, a pause and quiet.' },
    rev: { ru: 'Выгорание, беспокойство, пора вернуться к делам.', en: 'Burnout, restlessness and time to re-engage.' } },
  { id: 54, suit: 'swords', emoji: '⚔️',
    name: { ru: 'Пятёрка Мечей', en: 'Five of Swords' },
    up:  { ru: 'Конфликт, пиррова победа, эго и потери.', en: 'Conflict, a hollow victory, ego and loss.' },
    rev: { ru: 'Примирение, желание мира, извлечённый урок.', en: 'Reconciliation, a wish for peace and a lesson learned.' } },
  { id: 55, suit: 'swords', emoji: '⚔️',
    name: { ru: 'Шестёрка Мечей', en: 'Six of Swords' },
    up:  { ru: 'Переход, движение к лучшему, оставление трудностей позади.', en: 'Transition, moving towards calmer waters and leaving troubles behind.' },
    rev: { ru: 'Сопротивление переменам, незавершённый переход.', en: 'Resistance to change and an unfinished transition.' } },
  { id: 56, suit: 'swords', emoji: '⚔️',
    name: { ru: 'Семёрка Мечей', en: 'Seven of Swords' },
    up:  { ru: 'Хитрость, стратегия, тайные действия или обман.', en: 'Cunning, strategy, stealth or deception.' },
    rev: { ru: 'Разоблачение, признание, отказ от уловок.', en: 'Exposure, confession and abandoning deceit.' } },
  { id: 57, suit: 'swords', emoji: '⚔️',
    name: { ru: 'Восьмёрка Мечей', en: 'Eight of Swords' },
    up:  { ru: 'Ограничения, ловушка ума, чувство беспомощности.', en: 'Restriction, a mental trap and feeling powerless.' },
    rev: { ru: 'Освобождение, новый взгляд, выход из ловушки.', en: 'Release, new perspective and breaking free.' } },
  { id: 58, suit: 'swords', emoji: '⚔️',
    name: { ru: 'Девятка Мечей', en: 'Nine of Swords' },
    up:  { ru: 'Тревога, бессонница, страхи и переживания.', en: 'Anxiety, insomnia, fear and worry.' },
    rev: { ru: 'Облегчение, преодоление страхов, надежда.', en: 'Relief, overcoming fears and renewed hope.' } },
  { id: 59, suit: 'swords', emoji: '⚔️',
    name: { ru: 'Десятка Мечей', en: 'Ten of Swords' },
    up:  { ru: 'Болезненный конец, дно, но за ним рассвет.', en: 'A painful ending, rock bottom — but dawn follows.' },
    rev: { ru: 'Восстановление, подъём, худшее позади.', en: 'Recovery, rising again and the worst behind you.' } },
  { id: 60, suit: 'swords', emoji: '⚔️',
    name: { ru: 'Паж Мечей', en: 'Page of Swords' },
    up:  { ru: 'Любознательность, бдительность, новые идеи и острый ум.', en: 'Curiosity, vigilance, new ideas and a sharp mind.' },
    rev: { ru: 'Сплетни, поспешность, рассеянность.', en: 'Gossip, haste and scattered thinking.' } },
  { id: 61, suit: 'swords', emoji: '⚔️',
    name: { ru: 'Рыцарь Мечей', en: 'Knight of Swords' },
    up:  { ru: 'Решительность, напор, быстрые действия и амбиции.', en: 'Determination, drive, fast action and ambition.' },
    rev: { ru: 'Безрассудство, агрессия, спешка без плана.', en: 'Recklessness, aggression and haste without a plan.' } },
  { id: 62, suit: 'swords', emoji: '⚔️',
    name: { ru: 'Королева Мечей', en: 'Queen of Swords' },
    up:  { ru: 'Ясность ума, независимость, честность и проницательность.', en: 'Clear thinking, independence, honesty and perception.' },
    rev: { ru: 'Холодность, резкость, излишняя критичность.', en: 'Coldness, harshness and over-criticism.' } },
  { id: 63, suit: 'swords', emoji: '⚔️',
    name: { ru: 'Король Мечей', en: 'King of Swords' },
    up:  { ru: 'Логика, авторитет, справедливость и интеллект.', en: 'Logic, authority, fairness and intellect.' },
    rev: { ru: 'Манипуляция, тирания мысли, злоупотребление властью.', en: 'Manipulation, cold tyranny and abuse of power.' } },

  /* ============ ПЕНТАКЛИ / PENTACLES (земля, материя) ============ */
  { id: 64, suit: 'pentacles', emoji: '🪙',
    name: { ru: 'Туз Пентаклей', en: 'Ace of Pentacles' },
    up:  { ru: 'Новая возможность, достаток, начало в деньгах или деле.', en: 'A new opportunity, prosperity and a fresh material start.' },
    rev: { ru: 'Упущенный шанс, нестабильность, плохие вложения.', en: 'Missed opportunity, instability and poor investment.' } },
  { id: 65, suit: 'pentacles', emoji: '🪙',
    name: { ru: 'Двойка Пентаклей', en: 'Two of Pentacles' },
    up:  { ru: 'Баланс, жонглирование делами, гибкость и приоритеты.', en: 'Balance, juggling priorities, flexibility and adaptability.' },
    rev: { ru: 'Перегрузка, дисбаланс, потеря контроля над делами.', en: 'Overwhelm, imbalance and losing control of commitments.' } },
  { id: 66, suit: 'pentacles', emoji: '🪙',
    name: { ru: 'Тройка Пентаклей', en: 'Three of Pentacles' },
    up:  { ru: 'Командная работа, мастерство, сотрудничество и рост.', en: 'Teamwork, craftsmanship, collaboration and growth.' },
    rev: { ru: 'Разлад в команде, низкое качество, отсутствие признания.', en: 'Team conflict, poor quality and lack of recognition.' } },
  { id: 67, suit: 'pentacles', emoji: '🪙',
    name: { ru: 'Четвёрка Пентаклей', en: 'Four of Pentacles' },
    up:  { ru: 'Стабильность, бережливость, контроль над ресурсами.', en: 'Stability, saving and control over resources.' },
    rev: { ru: 'Жадность, скупость или, наоборот, бесконтрольные траты.', en: 'Greed, stinginess — or conversely, reckless spending.' } },
  { id: 68, suit: 'pentacles', emoji: '🪙',
    name: { ru: 'Пятёрка Пентаклей', en: 'Five of Pentacles' },
    up:  { ru: 'Трудности, нужда, чувство изоляции и потеря опоры.', en: 'Hardship, need, isolation and loss of support.' },
    rev: { ru: 'Восстановление, помощь приходит, конец трудностей.', en: 'Recovery, help arriving and the end of hardship.' } },
  { id: 69, suit: 'pentacles', emoji: '🪙',
    name: { ru: 'Шестёрка Пентаклей', en: 'Six of Pentacles' },
    up:  { ru: 'Щедрость, помощь, баланс давать и брать.', en: 'Generosity, support and the balance of giving and receiving.' },
    rev: { ru: 'Долги, неравенство, корыстная щедрость.', en: 'Debt, inequality and strings-attached generosity.' } },
  { id: 70, suit: 'pentacles', emoji: '🪙',
    name: { ru: 'Семёрка Пентаклей', en: 'Seven of Pentacles' },
    up:  { ru: 'Терпение, оценка вложений, долгосрочный рост.', en: 'Patience, assessing investment and long-term growth.' },
    rev: { ru: 'Нетерпение, плохие вложения, разочарование в результатах.', en: 'Impatience, poor investment and disappointing results.' } },
  { id: 71, suit: 'pentacles', emoji: '🪙',
    name: { ru: 'Восьмёрка Пентаклей', en: 'Eight of Pentacles' },
    up:  { ru: 'Мастерство, усердие, обучение и качественный труд.', en: 'Mastery, diligence, learning and quality work.' },
    rev: { ru: 'Перфекционизм, рутина без смысла, халтура.', en: 'Perfectionism, soulless routine or cutting corners.' } },
  { id: 72, suit: 'pentacles', emoji: '🪙',
    name: { ru: 'Девятка Пентаклей', en: 'Nine of Pentacles' },
    up:  { ru: 'Достаток, независимость, награда за труд и комфорт.', en: 'Abundance, independence, reward for effort and comfort.' },
    rev: { ru: 'Финансовая зависимость, переработки, пустой блеск.', en: 'Financial dependence, overwork and hollow luxury.' } },
  { id: 73, suit: 'pentacles', emoji: '🪙',
    name: { ru: 'Десятка Пентаклей', en: 'Ten of Pentacles' },
    up:  { ru: 'Богатство, наследие, семья и долгосрочная стабильность.', en: 'Wealth, legacy, family and lasting stability.' },
    rev: { ru: 'Финансовые споры, потеря наследия, нестабильность.', en: 'Financial disputes, lost legacy and instability.' } },
  { id: 74, suit: 'pentacles', emoji: '🪙',
    name: { ru: 'Паж Пентаклей', en: 'Page of Pentacles' },
    up:  { ru: 'Новые знания, амбиции, обучение и практичные планы.', en: 'New knowledge, ambition, study and practical plans.' },
    rev: { ru: 'Прокрастинация, нереализованные планы, лень.', en: 'Procrastination, unrealised plans and laziness.' } },
  { id: 75, suit: 'pentacles', emoji: '🪙',
    name: { ru: 'Рыцарь Пентаклей', en: 'Knight of Pentacles' },
    up:  { ru: 'Надёжность, трудолюбие, методичность и ответственность.', en: 'Reliability, hard work, method and responsibility.' },
    rev: { ru: 'Застой, скука, излишняя осторожность или лень.', en: 'Stagnation, boredom and over-caution or laziness.' } },
  { id: 76, suit: 'pentacles', emoji: '🪙',
    name: { ru: 'Королева Пентаклей', en: 'Queen of Pentacles' },
    up:  { ru: 'Забота, практичность, уют и финансовая мудрость.', en: 'Nurturing, practicality, comfort and financial sense.' },
    rev: { ru: 'Самопожертвование, дисбаланс работы и дома, тревога.', en: 'Self-neglect, work-life imbalance and anxiety.' } },
  { id: 77, suit: 'pentacles', emoji: '🪙',
    name: { ru: 'Король Пентаклей', en: 'King of Pentacles' },
    up:  { ru: 'Достаток, надёжность, деловая хватка и щедрость.', en: 'Prosperity, reliability, business sense and generosity.' },
    rev: { ru: 'Жадность, материализм, упрямство и контроль.', en: 'Greed, materialism, stubbornness and control.' } },
];

// Расклады / Spreads — позиции с подписями на двух языках.
const TAROT_SPREADS = {
  one: {
    name: { ru: 'Карта дня', en: 'Card of the Day' },
    positions: [
      { ru: 'Карта дня', en: 'Card of the Day' },
    ],
  },
  three: {
    name: { ru: 'Три карты', en: 'Three Cards' },
    positions: [
      { ru: 'Прошлое', en: 'Past' },
      { ru: 'Настоящее', en: 'Present' },
      { ru: 'Будущее', en: 'Future' },
    ],
  },
  situation: {
    name: { ru: 'Ситуация', en: 'Situation' },
    positions: [
      { ru: 'Ситуация', en: 'Situation' },
      { ru: 'Препятствие', en: 'Obstacle' },
      { ru: 'Совет', en: 'Advice' },
    ],
  },
  cross: {
    name: { ru: 'Кельтский крест', en: 'Celtic Cross' },
    positions: [
      { ru: '1. Суть', en: '1. The heart' },
      { ru: '2. Вызов', en: '2. The challenge' },
      { ru: '3. Основа (прошлое)', en: '3. Foundation (past)' },
      { ru: '4. Недавнее прошлое', en: '4. Recent past' },
      { ru: '5. Возможное будущее', en: '5. Possible outcome' },
      { ru: '6. Ближайшее будущее', en: '6. Near future' },
      { ru: '7. Вы сами', en: '7. Yourself' },
      { ru: '8. Окружение', en: '8. Environment' },
      { ru: '9. Надежды и страхи', en: '9. Hopes & fears' },
      { ru: '10. Итог', en: '10. Final outcome' },
    ],
  },
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { TAROT_DECK, TAROT_SPREADS };
}
